@baseUrl = http://localhost:3333
@authToken = {{auth.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Victor Prado",
  "email": "prado.victor@gmail.com",
  "password": "1234"
}

###
# @name auth
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "prado.victor@gmail.com",
  "password": "1234"
}

###
# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 3",
  "content": "Conteúdo da pergunta"
}

###
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}